name: CI Test Workflow

on:
  pull_request:
    branches:
      - '**'  # This pattern matches all branches
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Cache Python environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-python-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('.gitmodules') }}
          restore-keys: |
              ${{ runner.os }}-python-${{ hashFiles('scripts/setup.sh') }}-${{ hashFiles('.gitmodules') }}
              ${{ runner.os }}-python-${{ hashFiles('scripts/setup.sh') }}
              ${{ runner.os }}-python-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check formatting
        working-directory: ./client-rs
        run: cargo fmt --all -- --check

      - name: Run clippy
        working-directory: ./client-rs
        run: cargo clippy -- -D warnings

      - name: Install Dependencies
        run: make setup
        
      - name: Activate virtual environment
        run: source venv/bin/activate
        
      - name: Check formatting
        run: source venv/bin/activate && ./scripts/check_format.sh

      - name: Build Cairo-Zero
        run: source venv/bin/activate && make build-epoch && make build-committee

      - name: Run Cairo-Zero tests
        run: source venv/bin/activate && make test
      
